name: Trigger auto deployment for n8n-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/n8n-container-AutoDeployTrigger-af626e4e-41f6-4358-9b7d-3f468ceacf11.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.N8NCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.N8NCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.N8NCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.N8NCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.N8NCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: n8n-container
          resourceGroup: AmibouGroup
          imageToBuild: ameen.b@gmail.com/n8n-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


